### ISSUE TITLE
[AddBgmOnDialogue] 대사에 BGM 추가하기

### ISSUE THREAD

**Issue by hyeongjun3** [ThatFace2/WakPacking#4]
### 개요
- 대사가 시작할 때 BGM이 나올 수 있게 추가합니다. 애니메이션 X

### 기능 + 테스트 리스트
- [ ] 기존 BGM에 겹쳐서 재생
- [ ] 기존 BGM을 일시 정지하고 재생
- [ ] 해당 BGM이 멈추면 기존 BGM 다시 재생 여부

---
### 시간 트래킹(선택사항) 
- 예상 : 4H
- 시작 :  
- 끝     : 

### TODO(선택사항)
- 

### 참고자료(선택사항)
-
