### ISSUE TITLE
[MainBgm] BGM 출력

### ISSUE THREAD

**Issue by hyeongjun3** [ThatFace2/WakPacking#5]
### 개요
- 매인 BGM에 출력될 수 있는 시스템을 구현

### 기능 + 테스트 리스트
- [ ] On/Off 기능
- [ ] 다음 곡 기능, 이전 곡 기능
- [ ] 음량 조절 기능
- [ ] 자동 재생 기능

---
### 시간 트래킹(선택사항) 
- 예상 : 4H
- 시작 :  
- 끝     : 

### TODO(선택사항)
- 

### 참고자료(선택사항)
-
